BEGIN TRANSACTION;
DROP TABLE IF EXISTS `Invite`;
CREATE TABLE IF NOT EXISTS `Invite` (
	`Timestamp`	TEXT NOT NULL,
	`Username`	TEXT NOT NULL,
	`Purpose`	TEXT NOT NULL,
	`IP`	TEXT NOT NULL,
	`UA`	TEXT NOT NULL,
	`Language`	TEXT NOT NULL,
	`Reference`	TEXT NOT NULL,
	`UUID`	TEXT NOT NULL
);
DROP TABLE IF EXISTS `Hit`;
CREATE TABLE IF NOT EXISTS `Hit` (
	`Timestamp`	TEXT NOT NULL,
	`IP`	TEXT NOT NULL,
	`UUID`	TEXT NOT NULL
);
DROP TABLE IF EXISTS `Ban`;
CREATE TABLE IF NOT EXISTS `Ban` (
	`Timestamp`	TEXT NOT NULL,
	`IP`	TEXT NOT NULL,
	`UUID`	TEXT NOT NULL,
	`Reason`	TEXT,
	UNIQUE(IP, UUID)
);
COMMIT;
